import { NextResponse } from 'next/server';

const courses = [
  {
    id: 1,
    title: 'Python for Beginners',
    description: 'Learn Python programming from scratch with hands-on projects.',
    image: 'https://via.placeholder.com/300x150?text=Python+Course',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    learners: 12000,
    rating: 4.8,
    category: 'Technology',
    level: 'Beginner',
    isCertification: true,
    summary: 'This course covers Python basics, including variables, loops, and functions.',
    interested: true,
    recommended: true,
    isCompleted: true,
  },
  {
    id: 2,
    title: 'Advanced AI Techniques',
    description: 'Explore advanced AI concepts like neural networks and deep learning.',
    image: 'https://via.placeholder.com/300x150?text=AI+Course',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    learners: 8500,
    rating: 4.9,
    category: 'Technology',
    level: 'Advanced',
    isCertification: true,
    summary: 'Dive into AI with topics like neural networks, NLP, and computer vision.',
    interested: true,
    recommended: true,
    isCompleted: false,
  },
  {
    id: 3,
    title: 'Business Analytics',
    description: 'Master data analysis for business decision-making.',
    image: 'https://via.placeholder.com/300x150?text=Business+Analytics',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    learners: 9500,
    rating: 4.6,
    category: 'Business',
    level: 'Intermediate',
    isCertification: false,
    summary: 'Learn to analyze data and make informed business decisions.',
    recommended: true,
  },
  {
    id: 4,
    title: 'Web Development Bootcamp',
    description: 'Become a full-stack developer with this comprehensive bootcamp.',
    image: 'https://via.placeholder.com/300x150?text=Web+Development',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    learners: 15000,
    rating: 4.7,
    category: 'Technology',
    level: 'Intermediate',
    isCertification: true,
    summary: 'Covers HTML, CSS, JavaScript, and backend development.',
    isCompleted: true,
  },
  {
    id: 5,
    title: 'Digital Marketing',
    description: 'Learn the fundamentals of digital marketing and SEO.',
    image: 'https://via.placeholder.com/300x150?text=Digital+Marketing',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    learners: 7000,
    rating: 4.5,
    category: 'Business',
    level: 'Beginner',
    isCertification: false,
    summary: 'Understand SEO, social media marketing, and content strategies.',
  },
];

export async function GET() {
  return NextResponse.json(courses);
}   